#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3-pip
  - git
runcmd:
  - pip install ansible
  - cd /tmp/ && git clone --branch master https://github.com/dmitry231187/dos14-Stolyarov_Dmitry-git-flow.git authz
  - cd /tmp/authz/ansible && ansible-playbook playbook.yaml -i localhost, -c local

